version: '3.4'

services:
  pynyurl:
    image: pynyurl
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - ${APP_PORT}:${APP_PORT}
    environment:
      - POSTGRES_DB_NAME=${POSTGRES_DB_NAME}
      - POSTGRES_DB_USER=${POSTGRES_DB_USER}
      - POSTGRES_DB_PASS=${POSTGRES_DB_PASS}
      - POSTGRES_DB_PORT=${POSTGRES_DB_PORT}
      - APP_HOST=${APP_HOST}
      - APP_PORT=${APP_PORT}
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres
    restart: always
    user: ${POSTGRES_DB_USER}
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_USER=${POSTGRES_DB_USER}
      - POSTGRES_PASSWORD=${POSTGRES_DB_PASS}
    expose:
      - ${POSTGRES_DB_PORT}
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 10s
      retries: 10
volumes:
  db-data: